language: javascript

before_install:
  - chmod u+x build.sh
  - npm install --save-dev gulp
  - npm install --save-dev gulp-concat
  - npm install --save-dev gulp-uglify
  - npm install --save-dev gulp-react
  - npm install --save-dev gulp-html-replace
  - npm install --save-dev gulp-rename
  - npm install --save-dev gulp-order
  - sudo pip install ablog

script:
  - ./build.sh

after_success:
  - git config --global user.name "Andrew Schmitt"
  - git config --global user.email "aschmitt@berkeley.edu"
  - git config --global push.default simple
  - ablog deploy --push-quietly --github-token=DEPLOY_KEY -m="`git log -1 --pretty=%B`"