language: javascript

before_install:
  - chmod u+x build.sh
  - chmod u+x deploy.sh
  - bower install
  - npm i

script:
  - ./deploy.sh

after_success:
  - git config --global user.name "Andrew Schmitt"
  - git config --global user.email "aschmitt@berkeley.edu"
  - git config --global push.default simple
  - ablog deploy --push-quietly --github-token=DEPLOY_KEY -m="`git log -1 --pretty=%B`" -w='dist'